### PR TITLE
Load npy files asynchronously

### PR DESCRIPTION
**Pull request by jhughes982**
- Asynchronous loading wasn't working before. So I've converted the fileReader() to allow asynchronous loading,
 - Added support for loading in npy files for both C-contiguous and Fortran-contiguous array orders,
 - Updated readme

### CODE REVIEW

**Review by j6k4m8 — APPROVED** [review]
Very nice work! :) Let me run some local tests. Otherwise, are you ready to have this merged?

**Comment by jhughes982** [comment]
The only other consideration I had was that if there was a reason you did not want to add support for Fortran-contiguous orders you could instead catch it inside an error block.

But if Fortran order is fine I'm ready to merge.

**Comment by jhughes982** [comment]
I decided to return the contiguity order when you load in an npy file as this might be useful to some people.

**Comment by j6k4m8** [comment]
Super awesome, thank you for the contribution @jhughes982! Merging now :)

**Pull request merged**
