### PR TITLE
feat: add browser compatibility

### PR DESCRIPTION
**Pull request by WenheLI**
hi @j6k4m8 ! Thanks for this great project! I am looking for a js library that could both run on node & browser which could read `npy` file.

I just made a small commit to make this library node & browser compatible.
Comments are welcome!

Besides, I am working on another project that is to run/use data-processing & feature engineering ops within js. 
Here is the link: https://github.com/imgcook/datacook
Let me know how you think!

### CODE REVIEW

**Comment by WenheLI** [comment]
humms. To make this a real browser&node compatible module, we should add a bundler as well.

**Comment by j6k4m8** [comment]
Awesome @WenheLI — this is great! Thank you for adding. Ready to merge?

**Comment by j6k4m8** [comment]
@WenheLI just wanted to make sure everything's up to date here and this is ready to merge in?

**Comment by WenheLI** [comment]
Sorry that saw this thread! I still have some commits to push, could you give me a bit time?

**Comment by j6k4m8** [comment]
@WenheLI certainly, no rush! :)

**Comment by 1wheel** [comment]
As is, this PR works just fine in node and the browser (a global npyjs is added in the browser if loaded without bundler)—I think it is ready to merge to fix #10.

**Comment by j6k4m8** [comment]
@1wheel — thanks for the bump here!

**Comment by 1wheel** [comment]
@j6k4m8 Thanks for the quick response! Would you mind also bumping on npm?

**Comment by j6k4m8** [comment]
For sure, all done! `v0.2.0` is now live on npm. (Sorry for the delay, was away from my computer earlier and merged from mobile!)

**Pull request merged**
